### PR TITLE
💎support for templateAlias and cid in attachments

### LINKED ISSUE #11: Support for custom cid for attachments

### PR DESCRIPTION
**Pull request by gabrielstuff**
Hi, 
This pull request fixes #11 and #10 

I hope it follows your standard and you'll be able to publish soon.

Thanks,

Gabriel

### CODE REVIEW

**Comment by killmenot** [comment]
Hi @gabrielstuff Thank you for PR. Will look at this stuff in 1-2 days

**Comment by killmenot** [comment]
@gabrielstuff Nice work, really appreciated. Thank you for your contribution! v 2.1.0 published

**Comment by gabrielstuff** [comment]
Thank you for your work!
I was wondering if we should remove from the doc the postMarkOptions key as it is not implemented yet? 
Would be glad to help but not sure what options it should contains ?

**Comment by killmenot** [comment]
I will fix it. Thanks for that note. Postmark node lib was rewritten to TypeScript and links are 404 now. `postmarkOptions` is configuration object passed to the Postmark ServerClient. See references:
https://github.com/wildbit/postmark.js/blob/master/src/client/ServerClient.ts#L82
https://github.com/wildbit/postmark.js/blob/master/src/client/models/client/ClientOptions.ts
Seems I forgot to connect it in the past or ignored it by some reason. I dont think it will be wide used but at least want to allow users to be able to configure postmark client.

**Pull request merged**
